### ISSUE TITLE
Feature: Generate new API-key for user

### ISSUE THREAD

**Issue by Codehagen** [Codehagen/Dingify#11]

**Comment by Praashh** [comment]
hey @Codehagen what type of passkey we have to generate can you elaborate a bit with some ss ?

**Comment by Codehagen** [comment]
Hi @Praashh - I have been working on the component when a user first logs inn, they need to be able to generate a API key. 

```typescript
import { randomBytes } from 'crypto';

function generateApiKey(length: number = 32): string {
  // Create a buffer of random bytes
  const bytes = randomBytes(length);
  // Convert bytes to a hexadecimal string
  return bytes.toString('hex');
}

export default generateApiKey;
``` 
Need to update the prisma schema first.

**Comment by Praashh** [comment]
ok got it @Codehagen if noone isn't working on this issue, will happy to work upon that.

**Comment by Codehagen** [comment]
I need a way to copy the api key from the frontend and maybe make it so it displays **********.
Can make a issue now for you?
![Screenshot 2024-05-13@2x](https://github.com/Codehagen/Dingify/assets/24507211/6a822cbb-0e8a-4b82-b770-71abaa491de6)

**Comment by Codehagen** [comment]
@Praashh you can see the issue here #18

**Comment by Praashh** [comment]
ok let me give it a try.

**Comment by Codehagen** [comment]
Any questions @Praashh ? 😁

**Comment by Praashh** [comment]
not now sir , need to setup locally first is there any community channel of Dingify?

**Comment by Codehagen** [comment]
Hi @Praashh Somone started on this actully made it...
But I can make another one for you.
