### ISSUE TITLE
Fix: Change charts tooltip color for dark theme

### ISSUE THREAD

**Issue by Amirthananth** [Codehagen/Dingify#12]
Currently the tooltip for charts are having the same foreground and background color as light theme. Text is not properly visible
![image](https://github.com/Codehagen/Dingify/assets/22556726/2d533b57-ec3c-4874-90a4-9591cb6ad05c)

**Comment by Codehagen** [comment]
Yes, i saw that. 

If you want you can look at it? Here is some documentation for Nivo Charts theme: 

https://nivo.rocks/guides/theming/

**Comment by Amirthananth** [comment]
Sure. I'll take a look
