### ISSUE TITLE
Feature: Copy API key Component

### ISSUE THREAD

**Issue by Codehagen** [Codehagen/Dingify#18]
### Type of feature

💡 Feature

### Current behavior

Right now nothing happens when you press the "copy" component
![Screenshot 2024-05-13@2x](https://github.com/Codehagen/Dingify/assets/24507211/c7792c9e-d9ba-4c3d-b6e1-1c90c2f33579)

### Suggested solution

Make it so its possible to copy the API-key by just pressing the button-

![Screenshot 2024-05-13@2x](https://github.com/Codehagen/Dingify/assets/24507211/398ab25c-f7a4-418e-b609-8e4cf76358b9)

Also if possible make the input fields so its hides the API key
ApiKey
******************

**Comment by Amirthananth** [comment]
@Codehagen Can you assign it to me ? I can work on this.
