### ISSUE TITLE
Bug: Get started opens login modal for signed-in users

### ISSUE THREAD

**Issue by hiteshwadhwani** [Codehagen/Dingify#33]
### Describe the bug

On landing page when I clicked on get started it opened the sign-in modal but i was already signed in

<img width="1352" alt="image" src="https://github.com/Codehagen/Dingify/assets/82694988/416e5dc3-c3e6-4054-a800-1b16ebca9345">

### Steps to reproduce

After signing in click on get started on landing page

**Comment by Codehagen** [comment]
Thanks for the issue @hiteshwadhwani - Something you want to look at? ✨

**Comment by AkshayBandi027** [comment]
Hey! @Codehagen, I want to work this issue.  If user is authenticated then Getstarted button **redirects** user to docs ?

**Comment by Codehagen** [comment]
Redirect it to /dashboard after sign in. 

If they are signed in and press the button redirect to dashboard. 

You can write (.take) without the () to get assigned the issue 👍 @AkshayBandi027

**Comment by Codehagen** [comment]
You want it @AkshayBandi027? 👏🏻
