### ISSUE TITLE
Feature: Toast -> Sonner

### ISSUE THREAD

**Issue by Codehagen** [Codehagen/Dingify#52]
### Type of feature

🧑‍💻 Refactor

### Current behavior

The current implementation uses `useToast` for toast notifications in the application.

```typescript
import { useToast } from "@dingify/ui/components/use-toast";

export function AddChannelButton() {
  const { toast } = useToast();

  const handleSubmit = async (event) => {
    event.preventDefault();
    setIsLoading(true);

    try {
      const result = await createChannel(channelName);
      toast({
        title: "Channel Created",
        description: \`Channel "\${channelName}" created successfully.\`,
      });

```

### Suggested solution

Migrate all toast notifications from `useToast` to `sonner` as per the documentation [here](https://ui.shadcn.com/docs/components/sonner). Example bellow is just for illustration, but could work. 

**Steps:**

1. **Add the Toaster component:** Update your `app/layout.tsx` file:
   ```typescript
   import { Toaster } from "@/components/ui/sonner";

   export default function RootLayout({ children }) {
     return (
       <html lang="en">
         <head />
         <body>
           <main>{children}</main>
           <Toaster />
         </body>
       </html>
     );
   }
   ```

2. **Update toast notifications:** Replace the existing `useToast` implementation with `sonner`.

Updated code:

```typescript
import { toast } from "sonner";

export function AddChannelButton() {
 
    try {
      const result = await createChannel(channelName);

      toast.success(\`Channel "\${channelName}" created successfully.\`);

```

### Additional context

Replace all instances of `useToast` with `sonner` in the codebase to ensure consistent toast notifications.

**Comment by khAja13** [comment]
.take
