### ISSUE TITLE
Feature: Onboarding / Stepper for new users

### ISSUE THREAD

**Issue by Codehagen** [Codehagen/Dingify#72]
#### Current Behavior

Currently, we have some conditional rendering for when a new user doesn't have an API key. However, this needs improvement. Resend (www.resend.com) has a good method for handling this, as shown in the attached pictures.

#### Suggested Solution

Create a new page called `/onboarding` where we can display the steppers. We can use a horizontal stepper, such as the one found here: [ShadCN Stepper](https://shadcn-stepper.vercel.app/). The user can return to `/onboarding` if they want to go through the process again, so no state management in the database is needed for this.

Initial state for Resend:
![Initial state for Resend](https://github.com/Codehagen/Dingify/assets/24507211/e7abd6a2-913c-4c9e-aec6-80db41398a88)

Pressed Add API - This made the card green and then enabled the Send email button.
![Pressed Add API](https://github.com/Codehagen/Dingify/assets/24507211/56b41ac2-54c7-472d-97b4-a1daa54dda6d)

These boxes are also conditionally rendered based on if the person has pressed Send email and got a positive callback.
![Conditionally Rendered Boxes](https://github.com/Codehagen/Dingify/assets/24507211/dfbc849e-5059-4cfa-bda3-a76a3e56bbae)

We should have:
- **Step 1:** Add an API Key  
  _We can't create an event before this button is pressed, so we need to conditionally render it._  
- **Step 2:** Create a Channel  
  _Provide an input field and action to the database so a person can create a meaningful channel, e.g., sign up._
- **Step 3:** Create an Event  
  _Input their API key and the new channel in the call so this will be displayed._
- **Step 4:** Display Additional Actions  
  _Have some cards under to display more actions._

We need to reuse the make API key function, and we can use the same style as the `create-event` button that is currently on the homepage.

**Comment by AkshayBandi027** [comment]
.take

**Comment by Codehagen** [comment]
Hi @AkshayBandi027  - Do you have any questions regarding this issue? ✨

**Comment by Codehagen** [comment]
How is it going @AkshayBandi027 ?

**Comment by AkshayBandi027** [comment]
@Codehagen , I have created draft for this feature. I have few questions regrating  

**Step 4: Display Additional Actions
Have some cards under to display more actions.**

what actions needs to be displayed !! 
- any feedback would be appreciated.
